//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryTestApplication.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createStudent", ReplyAction="http://tempuri.org/IService1/createStudentResponse")]
        string createStudent(string Name, string LastName, string Details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createStudent", ReplyAction="http://tempuri.org/IService1/createStudentResponse")]
        System.Threading.Tasks.Task<string> createStudentAsync(string Name, string LastName, string Details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateStudentCourse", ReplyAction="http://tempuri.org/IService1/updateStudentCourseResponse")]
        string updateStudentCourse(string studentName, string courseCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateStudentCourse", ReplyAction="http://tempuri.org/IService1/updateStudentCourseResponse")]
        System.Threading.Tasks.Task<string> updateStudentCourseAsync(string studentName, string courseCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RepositoryTestApplication.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RepositoryTestApplication.ServiceReference1.IService1>, RepositoryTestApplication.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string createStudent(string Name, string LastName, string Details) {
            return base.Channel.createStudent(Name, LastName, Details);
        }
        
        public System.Threading.Tasks.Task<string> createStudentAsync(string Name, string LastName, string Details) {
            return base.Channel.createStudentAsync(Name, LastName, Details);
        }
        
        public string updateStudentCourse(string studentName, string courseCode) {
            return base.Channel.updateStudentCourse(studentName, courseCode);
        }
        
        public System.Threading.Tasks.Task<string> updateStudentCourseAsync(string studentName, string courseCode) {
            return base.Channel.updateStudentCourseAsync(studentName, courseCode);
        }
    }
}
